### PR TITLE
Create new branch before to archive

### PR DESCRIPTION
**Pull request by beenje**
I think it's easier to create the branch before to archive the project.
It's easy to delete it in GL after the import and avoid having to archive / unarchive / archive.

### CODE REVIEW

**Comment by beenje** [comment]
@cpascual what do you think?

**Comment by beenje** [comment]
Another thing. Can we update the `exclude` file to list all the users registered [here](https://mensuel.framapad.org/p/migration_ready_2548763689) ?
Would make it easier for the remaining repositories.

**Comment by cpascual** [comment]
> I think it's easier to create the branch before to archive the project.

I considered it, but I reasoned that strictly speaking it was best not to do such a change before everything is well checked and running in gitlab. IMHO, the price of a quick unarchiving/archiving at the time of doing the other final touches in github) is worth the  benefit of consistency.  But I don't have an strong opinion on it. If you still find it better the other way, please <s>submit a PR</s> say so and I'll merge this PR.

> Can we update the exclude file to list all the users registered here ?

I also considered it, but I didn't want to worry about updating it (pure lazyness).
Again, could you submit a PR?

Actually... the best thing would be to use some kind of wget to automatically fetch it at run time (just an idea!)

**Comment by cpascual** [comment]
Note: 
```wget https://mensuel.framapad.org/p/migration_ready_2548763689/export/txt && cat txt >> exclude``` 
should do the trick (I just updated the README to mention it)

**Comment by beenje** [comment]
I don't have a very strong opinion either.
@t-b and @bourtemb do you have a preference.

Regarding the list of registered users I updated the script to get it automatically: https://github.com/tango-controls/gitlab-migration-tools/pull/2

**Comment by t-b** [comment]
I always created the moved-to-gitlab branch before importing and never used unarchive.
I also changed the default branch in github before importing, so that gitlab already uses the correct default branch.

**Comment by cpascual** [comment]
Sorry, I forgot to recheck this. Since both @t-b and @beenje prefer the implementation from this PR, I am merging it.

**Pull request merged**
